name: Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Version tags"
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: pack for Station (@Silicon Valley)
        run: |
          cp -r . ../dist
          rm -rf ../dist/.git
          rm -rf ../dist/logs
          cp online.env ../dist/.env
          mkdir ../dist/db
          tar cvfz plm.tar.gz -C ../dist/ .

      - name: Push to Earth (@Beijing)
        uses: nogsantos/scp-deploy@master
        with:
          src: plm.tar.gz
          host: 139.199.30.36
          remote: /root/
          port: 22
          user: root
          key: ${{ secrets.SSH_KEY }}

      - name: Distribution
        uses: appleboy/ssh-action@master
        with:
          host: 139.199.30.36
          port: 22
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: rm -rf /data/plm && mkdir -p /data/plm/logs && cd /data/plm && tar xvfz /root/plm.tar.gz && yao migrate --reset --force && yao run scripts.demo.Data && supervisorctl reload
